/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejoarchivos;

/**
 *
 * @author Jose Caro
 */
public class Vista2 extends javax.swing.JFrame {

    /**
     * Creates new form Vista2
     */
    
    public Vista2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        IniciarAnalisis = new javax.swing.JLabel();
        AlmacenarResultado = new javax.swing.JLabel();
        Almacenar = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(51, 51, 51));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, 30));

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("El Software Negro de la Loteria");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 500, 60));

        IniciarAnalisis.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        IniciarAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        IniciarAnalisis.setText("Iniciar Analisis");
        getContentPane().add(IniciarAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 170, 30));

        AlmacenarResultado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AlmacenarResultado.setForeground(new java.awt.Color(255, 255, 255));
        AlmacenarResultado.setText("Almacenar Resultados");
        getContentPane().add(AlmacenarResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        Almacenar.setBackground(new java.awt.Color(51, 51, 51));
        Almacenar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Almacenar.setForeground(new java.awt.Color(255, 255, 255));
        Almacenar.setText("Almacenar");
        Almacenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenarActionPerformed(evt);
            }
        });
        getContentPane().add(Almacenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        Iniciar.setBackground(new java.awt.Color(51, 51, 51));
        Iniciar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        Iniciar.setText("Iniciar");
        Iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 120, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6326.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void AlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenarActionPerformed
        // TODO add your handling code here:
        Vista3 v3 = new Vista3();
        dispose();
        v3.setVisible(true);
        
    }//GEN-LAST:event_AlmacenarActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        Vista4 v4 = new Vista4();
        dispose();
        v4.setVisible(true);
        
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Almacenar;
    private javax.swing.JLabel AlmacenarResultado;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Iniciar;
    private javax.swing.JLabel IniciarAnalisis;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
