/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejoarchivos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Jose Caro
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    Vista2 v2;
    private Timer timer;
    private ActionListener ac;
    private int i=0;
    
    public Vista1() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               i++;
               BarraProgreso.setValue(i);
               if(BarraProgreso.getValue()== 1){
                   TextoCarga.setText("Cargando Presentacion.");
                   Vista2 vis2 = new Vista2();
               }
               
               if(BarraProgreso.getValue()== 25){
                   TextoCarga.setText("Cargando Almacenamiento.");
                   Vista3 vis3 = new Vista3();
               }
               
               if(BarraProgreso.getValue()== 50){
                   TextoCarga.setText("Cargando Analizador.");
                   Vista4 vis4 = new Vista4();
               }
               
               if(BarraProgreso.getValue()== 75){
                   TextoCarga.setText("Cargando Genarador N°.");
                   Vista5 vis5 = new Vista5();
               }
               if (BarraProgreso.getValue()==100){
                   dispose();
                   timer.stop();
                   v2 = new Vista2();
                   v2.setVisible(true);
                   
               }
            }
        };
        
        timer = new Timer(100, ac);
        timer.start();
       

    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraProgreso = new javax.swing.JProgressBar();
        Ing = new javax.swing.JLabel();
        TextoCarga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraProgreso.setBackground(new java.awt.Color(153, 153, 255));
        BarraProgreso.setForeground(new java.awt.Color(153, 153, 255));
        BarraProgreso.setBorderPainted(false);
        BarraProgreso.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BarraProgreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BarraProgresoFocusGained(evt);
            }
        });
        getContentPane().add(BarraProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 250, 20));

        Ing.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        Ing.setForeground(new java.awt.Color(255, 255, 255));
        Ing.setText("Ing: Jos'e Caro");
        getContentPane().add(Ing, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 40));

        TextoCarga.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(TextoCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 270, 20));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("welcome ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 70));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/b2.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraProgresoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BarraProgresoFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BarraProgresoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista1().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar BarraProgreso;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Ing;
    private javax.swing.JLabel TextoCarga;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
