/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejoarchivos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Caro
 */
public class Vista4 extends javax.swing.JFrame {

    /**
     * Creates new form Vista4
     */
    color col = new color();
    public Vista4() {
        initComponents();
        this.setLocationRelativeTo(null);
        Tabla.setDefaultRenderer(Object.class, col);
        TablaSinSalir.setDefaultRenderer(Object.class, col);
        TablaDuplos.setDefaultRenderer(Object.class, col);
        tabla();
        tabla1();
        tabla2();
    }

    void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("C1");
        modelo.addColumn("C2");
        modelo.addColumn("C3");
        modelo.addColumn("C4");

        Tabla.setModel(modelo);
        // TablaSinSalir.setModel(modelo);
    }

    void tabla1() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("C1");
        modelo.addColumn("C2");
        modelo.addColumn("C3");
        modelo.addColumn("C4");

        //Tabla.setModel(modelo);
        TablaSinSalir.setModel(modelo);
    }

    void tabla2() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Fecha");
        modelo.addColumn("C1");
        modelo.addColumn("C2");
        modelo.addColumn("C3");
        modelo.addColumn("C4");

        //Tabla.setModel(modelo);
        TablaDuplos.setModel(modelo);
        TablaDuplos.getColumnModel().getColumn(0).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Loterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSinSalir = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Apariciones = new javax.swing.JLabel();
        jPanelSinSalir = new javax.swing.JPanel();
        SinSalir = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDuplos = new javax.swing.JTable();
        Duplos = new javax.swing.JPanel();
        jLabelDuplos = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        Atras = new javax.swing.JMenuItem();
        Inicio = new javax.swing.JMenuItem();
        Cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, 190));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loteria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        Loterias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Loterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.", "Medellin.", "Santander.", "Cruz Roja.", "Chontico Dia.", "Chontico Noche.", "Paisita 1.", "Paisita 2.", "Paisita1 y 2", "Bogota.", "Quindio.", "Sinuano Dia.", "Sinuano Noche.", "Cundinamarca.", "Tolima.", "Huila.", "Valle.", "Manizales.", "Santander.", "Risaralda.", "Cauca.", "Boyaca." }));
        getContentPane().add(Loterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 190, -1));

        TablaSinSalir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaSinSalir);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 150, 190));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Apariciones.setBackground(new java.awt.Color(0, 0, 0));
        Apariciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Apariciones.setForeground(new java.awt.Color(255, 255, 255));
        Apariciones.setText("Apariciones por Sorteo");
        jPanel1.add(Apariciones);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 30));

        jPanelSinSalir.setBackground(new java.awt.Color(0, 0, 0));

        SinSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SinSalir.setForeground(new java.awt.Color(255, 255, 255));
        SinSalir.setText("Sorteos Sin Salir");
        jPanelSinSalir.add(SinSalir);

        getContentPane().add(jPanelSinSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 110, 30));

        TablaDuplos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaDuplos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 210, 190));

        Duplos.setBackground(new java.awt.Color(0, 0, 0));

        jLabelDuplos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelDuplos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDuplos.setText("Dobles F-C-E");
        Duplos.add(jLabelDuplos);

        getContentPane().add(Duplos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 90, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/17.png"))); // NOI18N
        Fondo.setToolTipText("");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Opciones.setText("Opciones-Analisis");
        Opciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Analisis por columna");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Opciones.add(jMenuItem1);

        jMenuItem2.setText("Generar Numero");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Opciones.add(jMenuItem2);

        jMenuBar1.add(Opciones);

        Salir.setText("   Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Atras.setText("Almacenar");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        Salir.add(Atras);

        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        Salir.add(Inicio);

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Salir.add(Cerrar);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        dispose();
        Vista3 v3 = new Vista3();
        v3.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        dispose();
        Vista2 v2 = new Vista2();
        v2.setVisible(true);
    }//GEN-LAST:event_InicioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Archivo objArchivo = new Archivo();
        String nombre = (String) Loterias.getSelectedItem();
        
        if(nombre.equals("Seleccione.")){
            JOptionPane.showMessageDialog(null,"Seleccione una Loteria");
        }else{
        
        String ruta = "C:\\BDLoterias\\" + nombre + ".txt";
        int nFilas = objArchivo.NumeroRegistros(ruta);
        

        if (nFilas > 0) {
            int opc = Integer.parseInt(JOptionPane.showInputDialog(null, "1. Estudio para Apostar \n2. Estudio Practico"));

            switch (opc) {
                case 1:
                    int valor = Integer.parseInt(JOptionPane.showInputDialog(null, "El archivo contiene " + nFilas + " Registros\nCon Cuantos registros\nDeseas hacer el análisis"));
                    String[][] mat = objArchivo.leer(ruta, valor);

                    if (valor >= 1 && valor <= nFilas) {

                        objArchivo.llenartabla(mat);
                        objArchivo.sorteosSinJugar(mat);
                        objArchivo.duplos(mat);


                    } else {
                        if (valor > nFilas) {
                            JOptionPane.showMessageDialog(null, "Excedio el numero de Registros");

                        } else {
                            JOptionPane.showMessageDialog(null, "Digite un Numero entre 1. y " + nFilas + ".");

                        }
                    }
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "Debe hacer el estudio con menos de 50 datos");
                    int n = Integer.parseInt(JOptionPane.showInputDialog(null, "Con cuantos datos desea hacer el estudio"));
                    if (n >= 1 && n < 50) {
                        //cambiar 30 por 50_______________________________________
                        String[][] matr = objArchivo.estudioPractico(ruta, n, 50);
                        objArchivo.llenartabla(matr);
                        objArchivo.sorteosSinJugar(matr);
                        objArchivo.duplos(matr);

                    } else {
                        if (n >= 50) {
                            JOptionPane.showMessageDialog(null, "Digite un numero menor a 50");
                        } else {
                            JOptionPane.showMessageDialog(null, "Digite un numero entre 1. y 50");
                        }
                    }
                    break;
                    default:
                        JOptionPane.showMessageDialog(null, "Digite un numero entre 1. y 2.");
            }
        }
        
        } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Vista5 v5 = new Vista5();
        dispose();
        v5.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apariciones;
    private javax.swing.JMenuItem Atras;
    private javax.swing.JMenuItem Cerrar;
    private javax.swing.JPanel Duplos;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem Inicio;
    private javax.swing.JComboBox<String> Loterias;
    private javax.swing.JMenu Opciones;
    private javax.swing.JMenu Salir;
    private javax.swing.JLabel SinSalir;
    public static javax.swing.JTable Tabla;
    public static javax.swing.JTable TablaDuplos;
    public static javax.swing.JTable TablaSinSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDuplos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSinSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
