/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejoarchivos;

import javax.swing.JOptionPane;

/**
 *
 * @author Jose Caro
 */
public class Vista5 extends javax.swing.JFrame {

    /**
     * Creates new form Vista5
     */
    public Vista5() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JLabel();
        Esfera1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        Esfera2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        Esfera3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        Esfera4 = new javax.swing.JLabel();
        Loterias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Generar1 = new javax.swing.JButton();
        Inicio = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 40, 60));

        Esfera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ESFERA2.png"))); // NOI18N
        Esfera1.setText("jLabel1");
        getContentPane().add(Esfera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 100));

        B2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 40, 60));

        Esfera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ESFERA2.png"))); // NOI18N
        Esfera2.setText("jLabel2");
        getContentPane().add(Esfera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, -1));

        B3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 40, 60));

        Esfera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ESFERA2.png"))); // NOI18N
        Esfera3.setText("jLabel1");
        getContentPane().add(Esfera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 110, -1));

        B4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, 60));

        Esfera4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ESFERA2.png"))); // NOI18N
        Esfera4.setText("jLabel1");
        getContentPane().add(Esfera4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 110, -1));

        Loterias.setBackground(new java.awt.Color(153, 153, 153));
        Loterias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Loterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.", "Medellin.", "Santander.", "Cruz Roja.", "Chontico Dia.", "Chontico Noche.", "Paisita 1.", "Paisita 2.", "Paisita1 y 2", "Bogota.", "Quindio.", "Sinuano Dia.", "Sinuano Noche.", "Cundinamarca.", "Tolima.", "Huila.", "Valle.", "Manizales.", "Santander.", "Risaralda.", "Cauca.", "Boyaca." }));
        getContentPane().add(Loterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 170, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loteria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 40));

        Generar1.setBackground(new java.awt.Color(0, 51, 51));
        Generar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Generar1.setForeground(new java.awt.Color(255, 255, 255));
        Generar1.setText("Generar N°");
        Generar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Generar1MouseClicked(evt);
            }
        });
        Generar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Generar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        Inicio.setBackground(new java.awt.Color(0, 51, 51));
        Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/17.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Generar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar1ActionPerformed

        

    }//GEN-LAST:event_Generar1ActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        Vista2 v2 = new Vista2();
        dispose();
        v2.setVisible(true);
    }//GEN-LAST:event_InicioActionPerformed
private static int opcion=0;
//bariable para pedir solo una ves. Numero para generar numeros
boolean bandera = true;
 static  int valor=0;
    private void Generar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generar1MouseClicked
        // TODO add your handling code here:
        
        Archivo objArchivo = new Archivo();
        String nombreLoteria = (String)Loterias.getSelectedItem();
        if(nombreLoteria.equals("Seleccione.")){
            JOptionPane.showMessageDialog(null, "Seleccione una Loteria.");
        }else{

        String nombre=(String)Loterias.getSelectedItem();
        String ruta;
        ruta = "C:\\BDLoterias\\" + nombre + ".txt";
        int nFilas = objArchivo.NumeroRegistros(ruta);
        
        if(bandera){
        valor = Integer.parseInt(JOptionPane.showInputDialog(null, "El archivo contiene " + nFilas + " Registros\nCon Cuantos registros\nDeseas Generar Numeros"));
        bandera=false;
        }
        System.out.println(valor);
        if(opcion<4){
            opcion++;
        }else{
            opcion=0;
        }
//            System.out.println(opcion);
        
         if(valor<=nFilas){

        switch(opcion){
            case 1:
                
//                nombre = (String)Loterias.getSelectedItem();
                ruta = "C:\\BDLoterias\\"+nombre+".txt";
                String ma [][]= objArchivo.leer(ruta, valor);
                objArchivo.generarNumero(ma,opcion);
                break;
                
            case 2:
        
//                nombre = (String)Loterias.getSelectedItem();
                ruta = "C:\\BDLoterias\\"+nombre+".txt";
                String ma1 [][]= objArchivo.leer(ruta, valor);
                objArchivo.generarNumero(ma1,opcion);
                break;
            case 3:
                
//                nombre = (String)Loterias.getSelectedItem();
                ruta = "C:\\BDLoterias\\"+nombre+".txt";
                String ma2 [][]= objArchivo.leer(ruta, valor);
                objArchivo.generarNumero(ma2,opcion);
                break;
            case 4:
                
//                nombre = (String)Loterias.getSelectedItem();
                ruta = "C:\\BDLoterias\\"+nombre+".txt";
                String ma3 [][]= objArchivo.leer(ruta, valor);
                objArchivo.generarNumero(ma3,opcion);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Solo es posible Generar 4 numeros");
       
        }
         }else{
             JOptionPane.showMessageDialog(null, "Digite un numero menor a "+nFilas);
              valor = Integer.parseInt(JOptionPane.showInputDialog(null, "El archivo contiene " + nFilas + " Registros\nCon Cuantos registros\nDeseas Generar Numeros"));
         }
        }
    }//GEN-LAST:event_Generar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel B1;
    public static javax.swing.JLabel B2;
    public static javax.swing.JLabel B3;
    public static javax.swing.JLabel B4;
    private javax.swing.JLabel Esfera1;
    private javax.swing.JLabel Esfera2;
    private javax.swing.JLabel Esfera3;
    private javax.swing.JLabel Esfera4;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Generar1;
    private javax.swing.JButton Inicio;
    private javax.swing.JComboBox<String> Loterias;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
