/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manejoarchivos;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static manejoarchivos.Vista4.Tabla;

/**
 *
 * @author Jose Caro
 */
public class Vista3 extends javax.swing.JFrame {

    /**
     * Creates new form Vista3
     */
    color col = new color();
    public Vista3() {
        initComponents();
        this.setLocationRelativeTo(null);
        tabla();
        Tabla.setDefaultRenderer(Object.class, col);
    }

    
     void tabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("FECHA");
        modelo.addColumn("C1");
        modelo.addColumn("C2");
        modelo.addColumn("C3");
        modelo.addColumn("C4");
        
        Tabla.setModel(modelo);
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(210);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Loteria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        C2 = new javax.swing.JSpinner();
        C3 = new javax.swing.JSpinner();
        C4 = new javax.swing.JSpinner();
        C1 = new javax.swing.JSpinner();
        Bajar = new javax.swing.JButton();
        Fecha = new com.toedter.calendar.JDateChooser();
        Guardar = new javax.swing.JButton();
        Inicio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Almacenar resultados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        Loteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Loteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.", "Medellin.", "Santander.", "Cruz Roja.", "Chontico Dia.", "Chontico Noche.", "Paisita 1.", "Paisita 2.", "Paisita1 y 2", "Bogota.", "Quindio.", "Sinuano Dia.", "Sinuano Noche.", "Cundinamarca.", "Tolima.", "Huila.", "Valle.", "Manizales.", "Santander.", "Risaralda.", "Cauca.", "Boyaca.", " ", " " }));
        Loteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoteriaActionPerformed(evt);
            }
        });
        getContentPane().add(Loteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 87, 190, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loterias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        C2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        C2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        C3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        C3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        C4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        C4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        C1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        C1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        Bajar.setBackground(new java.awt.Color(0, 51, 51));
        Bajar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bajar.setForeground(new java.awt.Color(255, 255, 255));
        Bajar.setText("Cargar");
        Bajar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajarActionPerformed(evt);
            }
        });
        getContentPane().add(Bajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 80, -1));
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, -1));

        Guardar.setBackground(new java.awt.Color(0, 51, 51));
        Guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        Inicio.setBackground(new java.awt.Color(0, 51, 51));
        Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Inicio");
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 80, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 290, 110));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/17.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoteriaActionPerformed

    private void BajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajarActionPerformed
        // TODO add your handling code here:

            Archivo objArchivo = new Archivo();
          
            String nombre =(String) Loteria.getSelectedItem();
            if(nombre.equals("Seleccione.")){
                JOptionPane.showMessageDialog(null, "Seleccione una Loteria.");
            }else{
            
            String ruta = "C:\\BDLoterias\\"+nombre+".txt";
            //objArchivo.leer(ruta);
            int nFilas= objArchivo.NumeroRegistros(ruta);
            
            String matz[][] = objArchivo.leer(ruta,nFilas);
            String nueva [][]= new String [matz.length][matz[0].length];
            int con = matz.length-1;
            if(nFilas > 0){
                for(int i =0;i<matz.length;i++){
                    //con = matz.length;
                    for(int j =0;j < matz[0].length;j++){
                        nueva [con][j] = matz [i][j];
                       
                    }
                     con--;
                }
            objArchivo.cargar(nueva);
            }
            
            }
        
    }//GEN-LAST:event_BajarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        Archivo objArchivo = new Archivo();
        
        String nombre = (String)Loteria.getSelectedItem();
        if(nombre.equals("Seleccione.")){
            JOptionPane.showMessageDialog(null, "Selecione una Loteria");
        }else{
        String informacion;
        //________________
        String dia = Integer.toString(Fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(Fecha.getCalendar().get(Calendar.MONTH )+1);
        String anio = Integer.toString(Fecha.getCalendar().get(Calendar.YEAR));
        if(Integer.parseInt(dia)<10){
            dia="0"+dia;
        }
         if(Integer.parseInt(mes)<9){
            mes="0"+mes;
        }
        String Datos;
        
        int B1, B2, B3,B4;
        B1 = Integer.parseInt(C1.getValue().toString());
        B2 = Integer.parseInt(C2.getValue().toString());
        B3 = Integer.parseInt(C3.getValue().toString());
        B4 = Integer.parseInt(C4.getValue().toString());
        
        String fecha = dia+"/"+mes+"/"+anio;
        Datos = fecha+","+B1+","+B2+","+B3+","+B4;
        //________________
        
        String ruta = "C:\\BDLoterias\\"+nombre+".txt";
        
        
        objArchivo.crearArchivo(ruta,Datos);
       // Texto.setText(null);
        Fecha.setCalendar(null);
        C1.setValue(0);
        C2.setValue(0);
        C3.setValue(0);
        C4.setValue(0);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        Vista2 v2 = new Vista2();
        v2.setVisible(true);
        dispose();
    }//GEN-LAST:event_InicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bajar;
    private javax.swing.JSpinner C1;
    private javax.swing.JSpinner C2;
    private javax.swing.JSpinner C3;
    private javax.swing.JSpinner C4;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Inicio;
    private javax.swing.JComboBox<String> Loteria;
    public static javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
